name: 22f3002948@ds.study.iitm.ac.in

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a sample action
      run: echo "Hello, 22f3002948@ds.study.iitm.ac.in!"
